### ISSUE TITLE
euclideanDistance is wrong

### ISSUE THREAD

**Issue by LovelyLich** [Unknowncmbk/DiscreteFrechetDistance#1]
Hi, thanks from your DFD implementation, it's very helpful to me.
But I found that euclideanDistance calculation is wrong. it should be math.sqrt(sum of (Point x - Point y)^2))
could you verify this ?

**Comment by Unknowncmbk** [comment]
You're welcome to make a pull request to change it. It's been two years since I've tackled this subject in college at Boston University, so I don't remember much. :)

**Comment by xcllin** [comment]
from up floor，your line 178~180 should be change “distance = Math.sqrt(Math.pow((i.dimensions[0] - j.dimensions[0]), 2) + Math.pow((i.dimensions[1] - j.dimensions[1]), 2))”；thanks your demo;my English is bad

**Comment by Unknowncmbk** [comment]
Edited!
